Blog App: validations and model specs
learnwithalfred/blog_ pull request #3
Opened 2022-10-27 10:46 UTC by learnwithalfred

## Completed Project requirements

- Add the following validations: ✔️ 
    - For the User model:
        - Name must not be blank.
        - PostsCounter must be an integer greater than or equal to zero.
    - For the Post model:  ✔️ 
        - Title must not be blank.
        - Title must not exceed 250 characters.
        - CommentsCounter must be an integer greater than or equal to zero.
        -  LikesCounter must be an integer greater than or equal to zero.

2022-10-27 10:49 UTC, DammyShittu commented
Hi @learnwithalfred,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly collaborate with your coding partner for this project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 12:23 UTC, learnwithalfred commented
Please did you check the project correctly?
![project](https://user-images.githubusercontent.com/34389326/198282717-c11ddf75-22e2-4209-963a-242247aa72f4.PNG)

This is the project I am submitting. It is a solo project

These are the requirements
![req](https://user-images.githubusercontent.com/34389326/198283038-d256cebe-b500-4d2b-a493-aba84be993ba.PNG)

Nowhere was it said that I should do the project with any partner.

2022-10-27 14:13 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @learnwithalfred 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🎯 
✔️ Descriptive PR
✔️ Done model validation
✔️ No linter errors
✔️ Good commit history

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:13 UTC, codepantha commented on spec/models/comment_spec.rb
> +    comment = FactoryBot.build(:comment, author_id: user.id, post_id: post.id)
- [ ] All your tests are running successfully as shown in the attached image below. Kindly take a look and try to fix it 👍 
![image](https://user-images.githubusercontent.com/46839548/198308902-ae1dc372-1539-4feb-b31e-403fe1e09f4f.png)

2022-10-28 06:56 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @learnwithalfred , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

### Highlights:
 ✔️ All specs are passing 
 ✔️ All linters are passing
 ✔️ Correct gitflow
 ✔️ Professional documentation

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![image](https://user-images.githubusercontent.com/77038610/192113752-c316f323-e076-4961-85fa-20b64eb8b6ed.png)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@shoirata] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 06:58 UTC, learnwithalfred commented
Thank you

2022-10-28 06:58 UTC, merged